version: '3.8'

services:
  my-app:
    build: ../05
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - my-app
    networks:
      - webnet

networks:
  webnet:
